dist: trusty
sudo: false
branches:
  only:
  - master
  - "/^v?([0-9]*)\\.([0-9]*)\\.([0-9]*)$/"
env:
  matrix:
  - TF_INPUT=false
  global:
  - secure: r1qvUWZAFL9HQctUU9U4B5nWE4eNasw/mNAmpHyGPcvLyoFcJpT32J2jpJCFMN0tDeMbX7WiGBWKoZ7/6n0r9bzXCTXwWEzqZ2AWh69dv3eRFFd9aMz+NF89XN3bNDewi4/YzLQJ0Vt8/GTffsmMM1+kZYYH5ayZJph35F2Kri0oDOAszKJF/KNrwvonxNVbSS+aPvEicz5lkm0hoDC8QetPWiJl7AWhxJmHj05qlARbKd/Xh22MryIYqrPCWW8oP+mXfZ0wiN9FxwYS1oEANq7N2gtwHEqqC0UMERAtxbqc8hmdoBUg9/qdhq7xbPxxya4ICKy22dkfP5e9+lc1YSUfbKRK8MEbWCcsqm0CMZUcksbqOTebSr2nUEbG7jCiVPdvwA0Hq673rSkFX8y2o7jC0yEM0Mj8bbewc3dJgDDq5yOAygB6pboNxRQeBT/89a1WoSKUE8Z3dRjjjo1QLJSVapjaeqzZuHIUKNU0REhEspyMZswf3UM/9F//7tyFV4Z5lSLa3ucgNpf4kkv0W51Z6R+/TY8O3QppqygRfciuBB55mVj8MwJxmKwWIxrlatuHgaoBUOBJUa5rAJRQ43C8m1wL/AF/wlpat2mKmifGJ8mcH+khx0hlaK447ZIJx9BLrkmirHt2pde24tuZFF87UokEXmnysJcssUDAKQ8=
  - secure: uKspYeDFcQhQUQhHGaJ1m+ZxifpAuSbjDaLNRxCHJ14dIvJ5TVUMlHxwx0AwD/ljyaobMBoYtrAprVkR03Q6OOANGtZdza/YpZSQUGbmgInIo2lCiRQaXWl/3qCfLlEsG0RpaU80he2W0XYwOKrR8UVezvUeZ7TGZNCOAj2zQ3RoAydDcUp7FVbvEGufkWO9AV45iQErH0JXqTlAajUHJ6gh+JyOCsqX7GER9BQjEUfjxJok+k2TzyFha0D8u1/yY+9TApNIUCMEQC/xkL8OsqCrYzO/woxognTJh7XgaeKw+BijZoMvw0jzl7sbIHS4jV877FS5gr9dwnuFGPr0KrXZ/PFqUeCHOWOEsYy5+i6zJ8kE82kmksse0XGIPVc7TavWthlybuWR0o5U8ZsuMj490KW7N0pr3t2yLxC98ELVBlmn77rgKKOUCQ/pssOSLhn/r0cZEkM3B7QyCkhA0Ir4B7hFc1nqFG/T7uYxFPNK7qW+8IdXEsx1Si354aWIWKo5RXtx7EfVQ3JJc2fKETiEs1UH6a1SaFa7XfUcriiu7MIYviF9Rh+/+6kK1VjDi4xu6NTxv1SoVrzbenBHAL7MlxohYjtPdpRbD7TpTBpjPMkl5GeU6Rf8XeeFPGVEn8sdsJ1MkU9iiVXjc05JT41nblV4jUz/JQLhJSspiLk=
before_install:
- curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.9.8/terraform_0.9.8_linux_amd64.zip
- unzip /tmp/terraform.zip -d /tmp
- mkdir ~/bin
- mv /tmp/terraform ~/bin
- export PATH="~/bin:$PATH"
script:
- terraform init
- terraform plan
deploy:
- provider: script
  skip_cleanup: true
  script: terraform apply ./terraform
  on:
    branch: master
